import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Aside from "./components/aside";
import Wrapper from "./components/wrapper";
import { Providers } from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={inter.className}>
        <Providers>
          <div className="flex">
            <Aside />
            <Wrapper>{children}</Wrapper>
          </div>
        </Providers>
      </body>
    </html>
  );
}
